In [5]:
import numpy as np
lst=[1,2,3]
lst1=[4,5,6]
arr=np.array([lst,lst1])
print(arr)

[[1 2 3]
 [4 5 6]]


In [7]:
arr.shape

(2, 3)

In [8]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
arr[0:,1:]

array([[2, 3],
       [5, 6]])

In [12]:
arr[:1,0:]

array([[1, 2, 3]])

In [36]:
arr2=np.arange(0,10,2)
print(arr2)

[0 2 4 6 8]


In [17]:
#Random Distribution prints only in b/w 0-1
np.random.rand(3,3)

array([[0.39234548, 0.97844037, 0.35608035],
       [0.29429334, 0.36106332, 0.03581078],
       [0.72031364, 0.38006733, 0.94384367]])

In [18]:
#Standard Normal Distribution
np.random.randn(3,3)

array([[-0.56785298, -2.181618  , -0.93199031],
       [-1.18543529, -0.06529801, -1.65684821],
       [-0.85237387, -1.31803316, -0.42187285]])

In [26]:
x=arr
print(x)
print("\n")
x[0:,1:]=100
print(x)
print("\n")
print(arr)

[[  1 100 100]
 [  4 100 100]]


[[  1 100 100]
 [  4 100 100]]


[[  1 100 100]
 [  4 100 100]]


In [28]:
x=arr.copy()
print(x)
print("\n")
x[0:,1:]=500
print(x)
print("\n")
print(arr)

[[  1 100 100]
 [  4 100 100]]


[[  1 500 500]
 [  4 500 500]]


[[  1 100 100]
 [  4 100 100]]


In [31]:
x=np.ones(4,dtype="int")
print(x)

[1 1 1 1]


In [38]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [20]:
import numpy as np
arr1=[1,2,3]
arr2=[5,4,6]
arr3=np.array([1,2,3,4,5,6,7,8])

print(arr3)
newarr = np.array_split(arr3, 3)
print(newarr)
x=np.where(arr==4)
print(x)
y=np.sort(arr2)
print(y)
arr4=np.array([True , False, True])
print(np.sort(arr4))

[1 2 3 4 5 6 7 8]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
(array([3], dtype=int64),)
[4 5 6]
[False  True  True]


In [25]:
import numpy as np
arr3=np.array([1,2,3,4,5,6,7,8])
x=arr3[[True,False,True,True,False,True,False,True,]]
print(x)

[1 3 4 6 8]


In [26]:
import numpy as np
q = np.array([30,40,37,49,55])
new=[]
for i in q:
    if i>40:
        new.append(True)
    else:
        new.append(False)
y=q[new]
print(y)

[49 55]
